return Def.ActorFrame{
	LoadActor(THEME:GetPathB("","ScreenWithMenuElements background/ddra_bg_hd"))..{
		OnCommand=cmd(FullScreen);
	};

	Def.ActorFrame{
		AnimOffCommand=cmd(diffusealpha,1;accelerate,0.4;diffusealpha,0);
		Def.Quad{
			InitCommand=cmd(FullScreen;diffuse,Color.White;diffusealpha,0.1;);
		};
		Def.Sprite{
			Texture=THEME:GetPathB("","_door/scsh_back_inter_blue"),
			InitCommand=function(self)
				self:FullScreen():diffusealpha(0.5)
				local w = DISPLAY:GetDisplayWidth() / self:GetWidth();
				local h = DISPLAY:GetDisplayHeight() / self:GetHeight();
				self:customtexturerect(2,0.8,w,h);
				self:texcoordvelocity(0,1);
			end;
		};
	};

	Def.ActorFrame{
		InitCommand=cmd(CenterX);	
	--UP
		LoadActor(THEME:GetPathB("","_door/scch_frame_blue.png"))..{
			InitCommand=cmd(x,378;y,SCREEN_TOP+80;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;y,SCREEN_TOP+163;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/scch_frame_blue.png"))..{
			InitCommand=cmd(x,-378;y,SCREEN_TOP+80;diffusealpha,0);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;y,SCREEN_TOP+163;diffusealpha,1;);
		};
	--FLASH
		LoadActor(THEME:GetPathB("","_door/scch_edge_flash_blue.png"))..{
			InitCommand=cmd(x,379;y,SCREEN_TOP+80;diffusealpha,0;zoom,-1);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;y,SCREEN_TOP+51;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/scch_edge_flash_blue.png"))..{
			InitCommand=cmd(x,-379;y,SCREEN_TOP+80;diffusealpha,0;zoomy,-1);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;y,SCREEN_TOP+51;diffusealpha,1;);
		};
	--DOWN
		LoadActor(THEME:GetPathB("","_door/scch_frame_blue.png"))..{
			InitCommand=cmd(x,378;y,SCREEN_BOTTOM-80;diffusealpha,0;zoom,-1);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;y,SCREEN_BOTTOM-126;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/scch_frame_blue.png"))..{
			InitCommand=cmd(x,-378;y,SCREEN_BOTTOM-80;diffusealpha,0;zoomy,-1);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;y,SCREEN_BOTTOM-126;diffusealpha,1;);
		};
	--FLASH
		LoadActor(THEME:GetPathB("","_door/scch_edge_flash_blue.png"))..{
			InitCommand=cmd(x,379;y,SCREEN_BOTTOM-80;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;y,SCREEN_BOTTOM-51;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/scch_edge_flash_blue.png"))..{
			InitCommand=cmd(x,-379;y,SCREEN_BOTTOM-80;diffusealpha,0);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;y,SCREEN_BOTTOM-51;diffusealpha,1;);
		};
	--DECORATIONS
	--LEFT
		LoadActor(THEME:GetPathB("","_door/coch_hud_side01.png"))..{
			InitCommand=cmd(x,-900;y,SCREEN_CENTER_Y-63);
			OnCommand=cmd(sleep,0.6;linear,0.1;x,-470);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_side02.png"))..{
			InitCommand=cmd(x,-900;y,SCREEN_CENTER_Y-63);
			OnCommand=cmd(sleep,0.6;linear,0.1;x,-538);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_side03.png"))..{
			InitCommand=cmd(x,-900;y,SCREEN_CENTER_Y-137);
			OnCommand=cmd(sleep,0.6;linear,0.1;x,-565);
		};
	--RIGHT
		LoadActor(THEME:GetPathB("","_door/coch_hud_side01.png"))..{
			InitCommand=cmd(x,900;y,SCREEN_CENTER_Y-63;zoomx,-1);
			OnCommand=cmd(sleep,0.6;linear,0.1;addx,-430);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_side02.png"))..{
			InitCommand=cmd(x,900;y,SCREEN_CENTER_Y-63;zoomx,-1);
			OnCommand=cmd(sleep,0.6;linear,0.1;addx,-362);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_side03.png"))..{
			InitCommand=cmd(x,900;y,SCREEN_CENTER_Y-137;zoomx,-1);
			OnCommand=cmd(sleep,0.6;linear,0.1;addx,-335);
		};
	--Up
		LoadActor(THEME:GetPathB("","_door/coch_hud_top02.png"))..{
			InitCommand=cmd(x,225;y,SCREEN_TOP-20;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;addy,230;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_top02.png"))..{
			InitCommand=cmd(x,-225;y,SCREEN_TOP-20;diffusealpha,0;);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;addy,230;diffusealpha,1;);
		};
	--Down
		LoadActor(THEME:GetPathB("","_door/coch_hud_under01.png"))..{
			InitCommand=cmd(x,426;y,SCREEN_BOTTOM-20;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_under01.png"))..{
			InitCommand=cmd(x,-426;y,SCREEN_BOTTOM-20;diffusealpha,0;);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
	--Up
		LoadActor(THEME:GetPathB("","_door/coch_hud_top01.png"))..{
			InitCommand=cmd(x,288;y,SCREEN_TOP+43;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;addy,80;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_top01.png"))..{
			InitCommand=cmd(x,-288;y,SCREEN_TOP+43;diffusealpha,0);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;addy,80;diffusealpha,1;);
		};
	--Down
		LoadActor(THEME:GetPathB("","_door/coch_hud_under02.png"))..{
			InitCommand=cmd(x,168;y,SCREEN_BOTTOM-133;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_under02.png"))..{
			InitCommand=cmd(x,-168;y,SCREEN_BOTTOM-133;diffusealpha,0;);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
	--Down
		LoadActor(THEME:GetPathB("","_door/coch_hud_under03.png"))..{
			InitCommand=cmd(x,262;y,SCREEN_BOTTOM-62;diffusealpha,0;zoomx,-1);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_under03.png"))..{
			InitCommand=cmd(x,-262;y,SCREEN_BOTTOM-62;diffusealpha,0;);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_centeru.png"))..{
			InitCommand=cmd(y,SCREEN_BOTTOM-29;diffusealpha,0;);
			OnCommand=cmd(addy,99;sleep,0.6;linear,0.1;addy,-145;diffusealpha,1;);
		};
		LoadActor(THEME:GetPathB("","_door/coch_hud_centerup.png"))..{
			InitCommand=cmd(y,SCREEN_TOP+59;diffusealpha,0;);
			OnCommand=cmd(addy,-99;sleep,0.6;linear,0.1;addy,80;diffusealpha,1;);
		};
	--LIGHT UP
		LoadActor(THEME:GetPathB("","_door/cosh_burst_flare_blue.png"))..{
			InitCommand=cmd(zoomx,1.4;zoomy,0.7;x,SCREEN_LEFT+20;y,SCREEN_TOP+38);
			OnCommand=cmd(diffusealpha,0;blend,Blend.Add;sleep,1.034;linear,0.3;diffusealpha,1;diffuseshift;effectcolor1,color("1,1,1,1");effectcolor2,color("1,1,1,0.9");effectperiod,0.02);
		};
	--LIGHT DOWN
		LoadActor(THEME:GetPathB("","_door/cosh_burst_flare_blue.png"))..{
			InitCommand=cmd(zoomx,1.4;zoomy,0.7;x,SCREEN_LEFT;y,SCREEN_BOTTOM+20);
			OnCommand=cmd(diffusealpha,0;blend,Blend.Add;sleep,1.034;linear,0.3;diffusealpha,1;diffuseshift;effectcolor1,color("1,1,1,1");effectcolor2,color("1,1,1,0.9");effectperiod,0.02);
		};
	};
}